name: CI PRs

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: github.repository == 'spring-projects-experimental/spring-pulsar'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Run Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build
      - name: Capture Test Results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '*/build/reports/tests/**/*.*'
          retention-days: 3
